"use client";

import React, { useState } from "react";
import Link from "next/link";
import { Sparkles, ArrowUpRight, CheckCircle2 } from "lucide-react";

type Category = "All" | "Electronics" | "Fashion" | "Home" | "Beauty" | "Food";

interface ExampleItem {
  id: string;
  category: Category;
  title: string;
  shotType: string;
  marketplace: string;
  icon: string;
  bgGradient: string;
  highlights: string[];
}

export const ExamplesGallery: React.FC = () => {
  const [activeTab, setActiveTab] = useState<Category>("All");

  const categories: Category[] = [
    "All",
    "Electronics",
    "Fashion",
    "Home",
    "Beauty",
    "Food",
  ];

  const examples: ExampleItem[] = [
    {
      id: "ex-1",
      category: "Electronics",
      title: "ANC Wireless Headphones Over-Ear",
      shotType: "Infographic: Acoustic Architecture",
      marketplace: "Amazon 2000x2000",
      icon: "🎧",
      bgGradient: "from-indigo-900/60 to-purple-950/60",
      highlights: ["40mm Graphene Drivers", "Hi-Res Audio Certified", "45ms Low Latency"],
    },
    {
      id: "ex-2",
      category: "Beauty",
      title: "Botanical Vitamin C Radiance Serum",
      shotType: "Lifestyle & Ingredient Breakdown",
      marketplace: "Amazon & Shopify",
      icon: "🧴",
      bgGradient: "from-pink-950/60 to-purple-900/60",
      highlights: ["Pure Kakadu Plum 20%", "Cruelty Free Verified", "Cold-Pressed Seed Oils"],
    },
    {
      id: "ex-3",
      category: "Home",
      title: "Ergonomic Cervical Contour Pillow",
      shotType: "Dimensions & Spine Alignment",
      marketplace: "Amazon A+",
      icon: "🛏️",
      bgGradient: "from-cyan-950/60 to-blue-950/60",
      highlights: ["Zero-Pressure Memory Foam", "Oeko-Tex Cover", "Side & Back Sleeper"],
    },
    {
      id: "ex-4",
      category: "Food",
      title: "Organic Ceremonial Grade Matcha",
      shotType: "Origin & Preparation Steps",
      marketplace: "Flipkart & Amazon",
      icon: "🍵",
      bgGradient: "from-emerald-950/60 to-teal-900/60",
      highlights: ["First Harvest Uji, Japan", "L-Theanine Energy", "Stone Ground Powder"],
    },
    {
      id: "ex-5",
      category: "Fashion",
      title: "Waterproof Minimalist Commuter Pack",
      shotType: "What's In The Box / Capacity",
      marketplace: "Shopify & Meesho",
      icon: "🎒",
      bgGradient: "from-slate-900 to-indigo-950/60",
      highlights: ["16-Inch Padded Sleeve", "YKK Aquaguard Zips", "Recycled Cordura"],
    },
    {
      id: "ex-6",
      category: "Beauty",
      title: "Rose Quartz Ultrasonic Facial Sculptor",
      shotType: "Comparison vs Traditional Rollers",
      marketplace: "Amazon Prime",
      icon: "✨",
      bgGradient: "from-rose-950/60 to-purple-900/60",
      highlights: ["12,000 VPM Micro-Vibrations", "Natural Grade-A Quartz", "USB-C Rechargeable"],
    },
  ];

  const filtered =
    activeTab === "All"
      ? examples
      : examples.filter((item) => item.category === activeTab);

  return (
    <section id="examples" className="py-24 bg-[#0B0B14] relative">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center max-w-3xl mx-auto mb-12">
          <span className="text-xs font-bold uppercase tracking-wider text-brand-violet bg-brand-violet/10 border border-brand-violet/20 px-3 py-1 rounded-full">
            Real Output Quality
          </span>
          <h2 className="mt-4 text-3xl sm:text-5xl font-extrabold font-heading text-white tracking-tight">
            Generated by Listone.ai for Top Sellers
          </h2>
          <p className="mt-4 text-base sm:text-lg text-slate-300">
            Browse real listing compositions generated from single product photographs across diverse categories.
          </p>
        </div>

        {/* Category Filter Tabs */}
        <div className="flex flex-wrap items-center justify-center gap-2 mb-12">
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => setActiveTab(cat)}
              className={`px-5 py-2 rounded-xl text-xs sm:text-sm font-semibold transition-all duration-200 ${
                activeTab === cat
                  ? "bg-gradient-to-r from-brand-indigo to-brand-violet text-white shadow-lg shadow-brand-violet/25"
                  : "bg-white/5 text-slate-400 hover:text-white hover:bg-white/10 border border-white/5"
              }`}
            >
              {cat}
            </button>
          ))}
        </div>

        {/* Gallery Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filtered.map((item) => (
            <div
              key={item.id}
              className="group rounded-3xl overflow-hidden bg-[#121223] border border-white/10 hover:border-brand-violet/50 shadow-xl transition-all duration-300 hover:-translate-y-2 flex flex-col justify-between"
            >
              {/* Product Visual Mockup */}
              <div
                className={`relative h-64 bg-gradient-to-br ${item.bgGradient} p-6 flex flex-col justify-between overflow-hidden border-b border-white/5`}
              >
                <div className="flex items-center justify-between z-10">
                  <span className="text-xs font-bold px-2.5 py-1 rounded-full bg-black/50 text-white backdrop-blur-md border border-white/10">
                    {item.shotType}
                  </span>
                  <span className="text-[11px] font-mono text-slate-300 bg-white/10 px-2 py-0.5 rounded">
                    {item.marketplace}
                  </span>
                </div>

                {/* Central Icon Asset */}
                <div className="my-auto mx-auto transform group-hover:scale-110 transition-transform duration-300 text-6xl drop-shadow-2xl">
                  {item.icon}
                </div>

                <div className="flex flex-wrap gap-1.5 z-10">
                  {item.highlights.map((h, i) => (
                    <span
                      key={i}
                      className="text-[10px] font-semibold text-slate-200 bg-black/40 px-2 py-0.5 rounded backdrop-blur-sm"
                    >
                      ✓ {h}
                    </span>
                  ))}
                </div>
              </div>

              {/* Card Meta Content */}
              <div className="p-6">
                <span className="text-[11px] font-bold text-brand-pink uppercase tracking-wider">
                  {item.category}
                </span>
                <h4 className="mt-1 text-base font-bold text-white group-hover:text-pink-100 transition-colors">
                  {item.title}
                </h4>

                <div className="mt-5 pt-4 border-t border-white/5 flex items-center justify-between">
                  <span className="text-xs text-slate-400 flex items-center gap-1">
                    <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                    Layered Canvas File
                  </span>
                  <Link
                    href={`/dashboard/image-studio`}
                    className="inline-flex items-center gap-1 text-xs font-bold text-brand-pink hover:text-white transition-colors"
                  >
                    <span>Test In Studio</span>
                    <ArrowUpRight className="w-3.5 h-3.5" />
                  </Link>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};
